CREATE FUNCTION IdFromURL(s TEXT) RETURNS CHAR(50) DETERMINISTIC RETURN REVERSE(SUBSTR(REVERSE(s), 1, LOCATE('/', REVERSE(s)) - 1));
CREATE FUNCTION IdFromURL2(s TEXT) RETURNS CHAR(250) DETERMINISTIC RETURN REVERSE(SUBSTR(REVERSE(s), 1, LOCATE('/', REVERSE(s)) - 1));

